### ISSUE TITLE
[Aurelia]キャラクターを複数対応出来るように対応する

### ISSUE THREAD

**Issue by arith-k-saito** [arith-alexander/solobure_frontend#7]
メイン画面の送信ボタンの横にキャラクター設定画面への遷移ボタン追加する

最初にキャラクターのidを選択してそこから必要項目を設定する

設定出来るキャラクターは３人。追加は別途対応。

キャラクター設定項目
- ~~id~~
- 名前
- 吹き出しの色

~~保存するのはwebのローカルストレージ~~

**Comment by arith-k-saito** [comment]
着手します。

**Comment by arith-y-ono** [comment]
https://github.com/arith-alexander/solobure_frontend/pull/20 にて対応ずみ
